import type { Category, Product } from "./types"

export const mockCategories: Category[] = [
  {
    id: "1",
    name_en: "Food & Groceries",
    name_krio: "Chɔp ɛn Tins fɔ It",
    slug: "food-groceries",
    icon: "🍚",
    display_order: 1,
  },
  {
    id: "2",
    name_en: "Fashion & Clothing",
    name_krio: "Klos ɛn Fashɔn",
    slug: "fashion-clothing",
    icon: "👕",
    display_order: 2,
  },
  {
    id: "3",
    name_en: "Handicrafts",
    name_krio: "We Dɛn Mek wit An",
    slug: "handicrafts",
    icon: "🎨",
    display_order: 3,
  },
  { id: "4", name_en: "Electronics", name_krio: "Ilɛktrik Tins", slug: "electronics", icon: "📱", display_order: 4 },
  {
    id: "5",
    name_en: "Beauty & Personal Care",
    name_krio: "Byuti ɛn Bɔdi Tin",
    slug: "beauty-personal-care",
    icon: "💄",
    display_order: 5,
  },
  { id: "6", name_en: "Home & Garden", name_krio: "Os ɛn Gadin", slug: "home-garden", icon: "🏠", display_order: 6 },
  {
    id: "7",
    name_en: "Books & Education",
    name_krio: "Buk ɛn Ɛdyukeshɔn",
    slug: "books-education",
    icon: "📚",
    display_order: 7,
  },
  {
    id: "8",
    name_en: "Sports & Outdoors",
    name_krio: "Spɔt ɛn Awtsay",
    slug: "sports-outdoors",
    icon: "⚽",
    display_order: 8,
  },
  { id: "9", name_en: "Toys & Kids", name_krio: "Pikin Tins", slug: "toys-kids", icon: "🧸", display_order: 9 },
  {
    id: "10",
    name_en: "Health & Wellness",
    name_krio: "Wɛlbɔdi",
    slug: "health-wellness",
    icon: "💊",
    display_order: 10,
  },
]

export const mockProducts: Product[] = [
  // Food & Groceries (Category 1)
  {
    id: "1",
    category_id: "1",
    name_en: "Fresh Cassava Leaves",
    name_krio: "Frɛsh Kasada Lif",
    description_en:
      "Fresh cassava leaves from local farms, perfect for making plasas. Rich in nutrients and harvested daily.",
    description_krio: "Frɛsh kasada lif frɔm lokal fam, fayn fɔ mek plasas",
    price: 15000,
    currency: "SLL",
    image_url: "/fresh-cassava-leaves-african-vegetable.jpg",
    stock_quantity: 100,
    is_active: true,
    is_featured: true,
    district: "Western Area",
    views_count: 245,
  },
  {
    id: "4",
    category_id: "1",
    name_en: "Palm Oil (Pure & Organic)",
    name_krio: "Palm Ɔyl (Klin ɛn Ɔganik)",
    description_en: "Locally processed pure red palm oil. 100% organic with no additives. Great for cooking.",
    description_krio: "Lokal palm ɔyl we dɛn prosɛs klin",
    price: 25000,
    currency: "SLL",
    image_url: "/red-palm-oil-bottle.jpg",
    stock_quantity: 50,
    is_active: true,
    is_featured: false,
    district: "Moyamba",
    views_count: 412,
  },
  {
    id: "7",
    category_id: "1",
    name_en: "Dried Fish (Bonga)",
    name_krio: "Dray Bɔnga",
    description_en: "Premium dried bonga fish, perfect for soups and stews. Cleaned and smoked.",
    description_krio: "Fayn dray bɔnga fish fɔ sup ɛn stew",
    price: 45000,
    currency: "SLL",
    image_url: "/dried-smoked-fish-african.jpg",
    stock_quantity: 35,
    is_active: true,
    is_featured: false,
    district: "Bonthe",
    views_count: 267,
  },
  {
    id: "9",
    category_id: "1",
    name_en: "Local Rice (50kg Bag)",
    name_krio: "Salone Rays (50kg Bag)",
    description_en: "Premium quality locally grown rice. Fresh harvest from northern farms. Clean and stone-free.",
    description_krio: "Fayn fayn lokal rays we dɛn gro na Salone",
    price: 450000,
    currency: "SLL",
    image_url: "/rice-bag-african.jpg",
    stock_quantity: 80,
    is_active: true,
    is_featured: true,
    district: "Kambia",
    views_count: 892,
  },
  {
    id: "10",
    category_id: "1",
    name_en: "Ground Pepper (Scotch Bonnet)",
    name_krio: "Grɔn Pɛpɛ",
    description_en: "Freshly ground scotch bonnet pepper. Very hot! Perfect for adding flavor to any dish.",
    description_krio: "Frɛsh grɔn pɛpɛ we hot bad bad",
    price: 8000,
    currency: "SLL",
    image_url: "/ground-hot-pepper-african.jpg",
    stock_quantity: 120,
    is_active: true,
    is_featured: false,
    district: "Freetown",
    views_count: 234,
  },
  {
    id: "11",
    category_id: "1",
    name_en: "Fresh Tomatoes (Per kg)",
    name_krio: "Frɛsh Tɔmato",
    description_en: "Fresh ripe tomatoes from local farms. Perfect for making stew or fresh salads.",
    description_krio: "Frɛsh tɔmato frɔm lokal fam",
    price: 12000,
    currency: "SLL",
    image_url: "/fresh-tomatoes-african.jpg",
    stock_quantity: 75,
    is_active: true,
    is_featured: false,
    district: "Bo",
    views_count: 189,
  },

  // Fashion & Clothing (Category 2)
  {
    id: "2",
    category_id: "2",
    name_en: "Traditional Gara Tie-Dye Fabric",
    name_krio: "Tradishɔnal Gara Klɔt",
    description_en:
      "Authentic Sierra Leonean gara fabric with beautiful patterns. Hand-dyed by skilled artisans in Bo.",
    description_krio: "Rial Salone gara klɔt wit fayn fayn patan dɛm",
    price: 80000,
    currency: "SLL",
    image_url: "/african-tie-dye-gara-fabric-blue-green.jpg",
    stock_quantity: 25,
    is_active: true,
    is_featured: true,
    district: "Bo",
    views_count: 532,
  },
  {
    id: "5",
    category_id: "2",
    name_en: "African Print Dress",
    name_krio: "Afrika Print Drɛs",
    description_en:
      "Stylish African print dress, made in Salone. Available in multiple sizes. Perfect for any occasion.",
    description_krio: "Fayn Afrika print drɛs, dɛn mek am na Salone",
    price: 120000,
    currency: "SLL",
    image_url: "/african-print-dress-woman-green-blue.jpg",
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 678,
  },
  {
    id: "12",
    category_id: "2",
    name_en: "Men's Traditional Agbada",
    name_krio: "Man Agbada",
    description_en:
      "Elegant traditional agbada outfit for men. Hand-tailored with quality fabric. Perfect for special occasions.",
    description_krio: "Fayn tradishɔnal agbada fɔ man",
    price: 250000,
    currency: "SLL",
    image_url: "/african-man-agbada-outfit.jpg",
    stock_quantity: 12,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 421,
  },
  {
    id: "13",
    category_id: "2",
    name_en: "Women's Head Wrap (Gele)",
    name_krio: "Uman Gele",
    description_en: "Beautiful African head wrap fabric. Multiple colors available. Easy to tie and style.",
    description_krio: "Fayn gele fɔ uman",
    price: 35000,
    currency: "SLL",
    image_url: "/african-head-wrap-gele-colorful.jpg",
    stock_quantity: 45,
    is_active: true,
    is_featured: false,
    district: "Bo",
    views_count: 312,
  },
  {
    id: "14",
    category_id: "2",
    name_en: "Children's School Uniform Set",
    name_krio: "Pikin Skul Yunifɔm",
    description_en: "Complete school uniform set for children. Includes shirt and shorts/skirt. Quality fabric.",
    description_krio: "Kɔmplit skul yunifɔm fɔ pikin",
    price: 75000,
    currency: "SLL",
    image_url: "/children-school-uniform.jpg",
    stock_quantity: 60,
    is_active: true,
    is_featured: false,
    district: "Makeni",
    views_count: 567,
  },
  {
    id: "15",
    category_id: "2",
    name_en: "Leather Sandals (Handmade)",
    name_krio: "Lɛda Sandal",
    description_en: "Comfortable handmade leather sandals. Made by local cobblers. Durable and stylish.",
    description_krio: "Kɔmfɔt lɛda sandal we dɛn mek wit an",
    price: 55000,
    currency: "SLL",
    image_url: "/handmade-leather-sandals-african.jpg",
    stock_quantity: 30,
    is_active: true,
    is_featured: false,
    district: "Kenema",
    views_count: 289,
  },

  // Handicrafts (Category 3)
  {
    id: "3",
    category_id: "3",
    name_en: "Handwoven Palm Basket",
    name_krio: "Basket we Dɛn Wiv wit Palm",
    description_en: "Beautiful handwoven basket made by local artisans. Perfect for shopping or home decoration.",
    description_krio: "Fayn basket we lokal pipul dɛm wiv wit dɛn an",
    price: 35000,
    currency: "SLL",
    image_url: "/african-handwoven-palm-basket.jpg",
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    district: "Kenema",
    views_count: 189,
  },
  {
    id: "8",
    category_id: "3",
    name_en: "Wooden Carving - Lion",
    name_krio: "Wud Karv - Layɔn",
    description_en: "Beautiful hand-carved wooden lion. Made from local hardwood by master craftsmen.",
    description_krio: "Fayn wud layɔn we dɛn karv wit an",
    price: 95000,
    currency: "SLL",
    image_url: "/african-wooden-lion-carving.jpg",
    stock_quantity: 8,
    is_active: true,
    is_featured: true,
    district: "Makeni",
    views_count: 156,
  },
  {
    id: "16",
    category_id: "3",
    name_en: "Traditional Drums (Djembe)",
    name_krio: "Tradishɔnal Drɔm",
    description_en: "Authentic handmade djembe drum. Perfect sound quality. Made by experienced drum makers.",
    description_krio: "Rial djembe drɔm we dɛn mek wit an",
    price: 180000,
    currency: "SLL",
    image_url: "/african-djembe-drum-traditional.jpg",
    stock_quantity: 6,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 223,
  },
  {
    id: "17",
    category_id: "3",
    name_en: "Beaded Jewelry Set",
    name_krio: "Bid Jwɛlri Sɛt",
    description_en: "Beautiful handmade beaded jewelry set. Includes necklace, earrings, and bracelet.",
    description_krio: "Fayn bid jwɛlri sɛt we dɛn mek wit an",
    price: 45000,
    currency: "SLL",
    image_url: "/african-beaded-jewelry-set-colorful.jpg",
    stock_quantity: 22,
    is_active: true,
    is_featured: false,
    district: "Bo",
    views_count: 334,
  },
  {
    id: "18",
    category_id: "3",
    name_en: "Woven Floor Mat",
    name_krio: "Wiv Mat",
    description_en: "Large handwoven floor mat. Durable and comfortable. Perfect for indoor use.",
    description_krio: "Big mat we dɛn wiv wit an",
    price: 65000,
    currency: "SLL",
    image_url: "/woven-floor-mat-african-traditional.jpg",
    stock_quantity: 18,
    is_active: true,
    is_featured: false,
    district: "Kailahun",
    views_count: 178,
  },
  {
    id: "19",
    category_id: "3",
    name_en: "Pottery Vase",
    name_krio: "Klɛ Pot fɔ Flawa",
    description_en: "Handmade pottery vase with traditional designs. Perfect for flowers or decoration.",
    description_krio: "Klɛ pot we dɛn mek wit an",
    price: 40000,
    currency: "SLL",
    image_url: "/african-pottery-vase-traditional-clay.jpg",
    stock_quantity: 14,
    is_active: true,
    is_featured: false,
    district: "Kenema",
    views_count: 145,
  },

  // Electronics (Category 4)
  {
    id: "20",
    category_id: "4",
    name_en: "Solar Power Bank (20000mAh)",
    name_krio: "Sola Pawa Bank",
    description_en:
      "High-capacity solar power bank. Charges phones and tablets. Perfect for areas with power challenges.",
    description_krio: "Big pawa bank we yuz sola layt",
    price: 95000,
    currency: "SLL",
    image_url: "/solar-power-bank-portable-charger.jpg",
    stock_quantity: 35,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 687,
  },
  {
    id: "21",
    category_id: "4",
    name_en: "LED Rechargeable Torch",
    name_krio: "LED Tɔch we Yuz Charj",
    description_en: "Bright LED torch with rechargeable battery. Long-lasting and waterproof.",
    description_krio: "Brayt LED tɔch we gɛt charj",
    price: 35000,
    currency: "SLL",
    image_url: "/led-rechargeable-torch-flashlight.jpg",
    stock_quantity: 50,
    is_active: true,
    is_featured: false,
    district: "Bo",
    views_count: 412,
  },
  {
    id: "22",
    category_id: "4",
    name_en: "Bluetooth Speaker",
    name_krio: "Blutut Spika",
    description_en: "Portable bluetooth speaker with powerful sound. Long battery life and waterproof design.",
    description_krio: "Pɔrtɛbul blutut spika wit big sawnd",
    price: 125000,
    currency: "SLL",
    image_url: "/portable-bluetooth-speaker-wireless.jpg",
    stock_quantity: 28,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 543,
  },
  {
    id: "23",
    category_id: "4",
    name_en: "Phone Accessories Bundle",
    name_krio: "Fon Aksɛsɔri Sɛt",
    description_en: "Complete phone accessories set: charger, cable, earphones, and screen protector.",
    description_krio: "Kɔmplit fon aksɛsɔri sɛt",
    price: 45000,
    currency: "SLL",
    image_url: "/phone-accessories-bundle-charger-earphones.jpg",
    stock_quantity: 75,
    is_active: true,
    is_featured: false,
    district: "Makeni",
    views_count: 621,
  },
  {
    id: "24",
    category_id: "4",
    name_en: "USB Fan (Mini)",
    name_krio: "USB Fan (Smɔl)",
    description_en: "Portable USB mini fan. Quiet and efficient. Perfect for desk or travel use.",
    description_krio: "Smɔl USB fan fɔ kip yu kul",
    price: 22000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 60,
    is_active: true,
    is_featured: false,
    district: "Freetown",
    views_count: 289,
  },
  {
    id: "25",
    category_id: "4",
    name_en: "Smart Watch",
    name_krio: "Smart Wach",
    description_en: "Affordable smart watch with fitness tracking, notifications, and long battery life.",
    description_krio: "Smart wach fɔ tɛl tɛm ɛn chɛk yu wɛlbɔdi",
    price: 150000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 756,
  },

  // Beauty & Personal Care (Category 5)
  {
    id: "6",
    category_id: "5",
    name_en: "Shea Butter (Natural)",
    name_krio: "Shea Bɔta (Nachral)",
    description_en: "100% natural shea butter for skin and hair. Moisturizing and nourishing.",
    description_krio: "100% nachral shea bɔta fɔ skin ɛn yɛ",
    price: 30000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 40,
    is_active: true,
    is_featured: false,
    district: "Kailahun",
    views_count: 321,
  },
  {
    id: "26",
    category_id: "5",
    name_en: "Black Soap (Dudu Osun)",
    name_krio: "Blak Sop",
    description_en: "Traditional African black soap. Natural ingredients. Great for all skin types.",
    description_krio: "Tradishɔnal blak sop fɔ wash bɔdi",
    price: 18000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 80,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 489,
  },
  {
    id: "27",
    category_id: "5",
    name_en: "Hair Extensions (Human Hair)",
    name_krio: "Yɛ Ikstɛnshɔn",
    description_en: "Premium quality human hair extensions. Natural look and feel. Multiple styles available.",
    description_krio: "Fayn uman yɛ fɔ put na yu yɛ",
    price: 180000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 25,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 892,
  },
  {
    id: "28",
    category_id: "5",
    name_en: "Coconut Oil (Pure)",
    name_krio: "Kokonat Ɔyl",
    description_en: "100% pure coconut oil. Perfect for hair, skin, and cooking. Locally processed.",
    description_krio: "Klin kokonat ɔyl fɔ yɛ ɛn skin",
    price: 25000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 55,
    is_active: true,
    is_featured: false,
    district: "Bo",
    views_count: 367,
  },
  {
    id: "29",
    category_id: "5",
    name_en: "Body Lotion Set",
    name_krio: "Bɔdi Loshɔn Sɛt",
    description_en: "Moisturizing body lotion set with natural ingredients. Refreshing scents.",
    description_krio: "Bɔdi loshɔn sɛt fɔ mek yu skin smɛl fayn",
    price: 45000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 42,
    is_active: true,
    is_featured: false,
    district: "Freetown",
    views_count: 278,
  },
  {
    id: "30",
    category_id: "5",
    name_en: "Makeup Set (Complete)",
    name_krio: "Mekɔp Sɛt",
    description_en: "Complete makeup set with foundation, lipstick, mascara, and eyeshadow. Quality products.",
    description_krio: "Kɔmplit mekɔp sɛt fɔ mek yu luk fayn",
    price: 95000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 30,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 634,
  },

  // Home & Garden (Category 6)
  {
    id: "31",
    category_id: "6",
    name_en: "Mosquito Net (Double)",
    name_krio: "Mɔskito Nɛt (Dɔbul)",
    description_en: "Large treated mosquito net for double bed. Provides excellent protection against malaria.",
    description_krio: "Big mɔskito nɛt fɔ dɔbul bɛd",
    price: 35000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 90,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 567,
  },
  {
    id: "32",
    category_id: "6",
    name_en: "Cooking Pot Set (Aluminum)",
    name_krio: "Kuk Pot Sɛt",
    description_en: "Durable aluminum cooking pot set. Includes 3 different sizes. Perfect for everyday cooking.",
    description_krio: "Strɔng aluminyɔm pot dɛm fɔ kuk",
    price: 85000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 45,
    is_active: true,
    is_featured: false,
    district: "Bo",
    views_count: 423,
  },
  {
    id: "33",
    category_id: "6",
    name_en: "Plastic Chairs (Set of 4)",
    name_krio: "Plastik Chɛya Sɛt",
    description_en: "Sturdy plastic chairs set. Stackable design. Perfect for indoor and outdoor use.",
    description_krio: "Strɔng plastik chɛya dɛm",
    price: 120000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 32,
    is_active: true,
    is_featured: false,
    district: "Makeni",
    views_count: 389,
  },
  {
    id: "34",
    category_id: "6",
    name_en: "Water Filter (Ceramic)",
    name_krio: "Wata Filta",
    description_en: "Ceramic water filter for clean drinking water. Easy to use and maintain.",
    description_krio: "Wata filta fɔ mek wata klin",
    price: 75000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 28,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 512,
  },
  {
    id: "35",
    category_id: "6",
    name_en: "Gardening Tools Set",
    name_krio: "Gadin Tul Sɛt",
    description_en: "Complete gardening tools set. Includes hoe, rake, shovel, and watering can.",
    description_krio: "Tul dɛm fɔ wok na gadin",
    price: 65000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 20,
    is_active: true,
    is_featured: false,
    district: "Kenema",
    views_count: 234,
  },
  {
    id: "36",
    category_id: "6",
    name_en: "Bed Sheets Set (Cotton)",
    name_krio: "Bɛd Shit Sɛt",
    description_en: "Soft cotton bed sheets set. Includes fitted sheet, flat sheet, and pillowcases.",
    description_krio: "Sɔft kɔtn bɛd shit sɛt",
    price: 55000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 38,
    is_active: true,
    is_featured: false,
    district: "Freetown",
    views_count: 345,
  },

  // Books & Education (Category 7)
  {
    id: "37",
    category_id: "7",
    name_en: "Sierra Leone History Book",
    name_krio: "Salone Istri Buk",
    description_en: "Comprehensive book on Sierra Leone's history from pre-colonial times to present.",
    description_krio: "Buk we tɔk bɔt Salone istri",
    price: 45000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 25,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 289,
  },
  {
    id: "38",
    category_id: "7",
    name_en: "Mathematics Textbook (Secondary)",
    name_krio: "Mats Buk fɔ Sɛkɔndri Skul",
    description_en: "Complete mathematics textbook for secondary school students. Aligned with national curriculum.",
    description_krio: "Mats buk fɔ sɛkɔndri skul pikin dɛm",
    price: 35000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 60,
    is_active: true,
    is_featured: false,
    district: "Bo",
    views_count: 478,
  },
  {
    id: "39",
    category_id: "7",
    name_en: "English Dictionary",
    name_krio: "Inglish Dikshɔnari",
    description_en: "Comprehensive English dictionary. Perfect for students and professionals.",
    description_krio: "Inglish dikshɔnari fɔ lɔn wɔd dɛm",
    price: 30000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 40,
    is_active: true,
    is_featured: false,
    district: "Freetown",
    views_count: 356,
  },
  {
    id: "40",
    category_id: "7",
    name_en: "Children's Story Books (Set of 5)",
    name_krio: "Pikin Stori Buk Sɛt",
    description_en: "Collection of 5 illustrated children's story books. Educational and entertaining.",
    description_krio: "5 pikin stori buk wit pikchɔ dɛm",
    price: 40000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 35,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 423,
  },
  {
    id: "41",
    category_id: "7",
    name_en: "Exercise Books (Pack of 10)",
    name_krio: "Rayt Buk Pak",
    description_en: "Quality exercise books for school. Pack of 10 books. Ruled pages.",
    description_krio: "10 rayt buk fɔ skul",
    price: 25000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 120,
    is_active: true,
    is_featured: false,
    district: "Bo",
    views_count: 567,
  },
  {
    id: "42",
    category_id: "7",
    name_en: "Krio Language Learning Book",
    name_krio: "Krio Langwej Lɔn Buk",
    description_en: "Learn Krio language with this comprehensive guide. Includes grammar, vocabulary, and phrases.",
    description_krio: "Lɔn fɔ tɔk Krio wit dis buk",
    price: 38000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 30,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 234,
  },

  // Sports & Outdoors (Category 8)
  {
    id: "43",
    category_id: "8",
    name_en: "Football (Official Size)",
    name_krio: "Futbɔl",
    description_en: "Quality official size football. Durable and perfect for matches and training.",
    description_krio: "Fayn futbɔl fɔ ple match",
    price: 45000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 55,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 678,
  },
  {
    id: "44",
    category_id: "8",
    name_en: "Running Shoes (Sports)",
    name_krio: "Rɔn Shuz",
    description_en: "Comfortable running shoes for sports and fitness. Available in multiple sizes.",
    description_krio: "Kɔmfɔt shuz fɔ rɔn ɛn ple spɔt",
    price: 85000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 40,
    is_active: true,
    is_featured: true,
    district: "Bo",
    views_count: 534,
  },
  {
    id: "45",
    category_id: "8",
    name_en: "Gym Workout Set",
    name_krio: "Jim Wokawt Sɛt",
    description_en: "Complete gym workout set: resistance bands, skipping rope, and yoga mat.",
    description_krio: "Kɔmplit gym sɛt fɔ wokawt",
    price: 95000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 28,
    is_active: true,
    is_featured: false,
    district: "Freetown",
    views_count: 412,
  },
  {
    id: "46",
    category_id: "8",
    name_en: "Basketball",
    name_krio: "Basketbɔl",
    description_en: "Quality basketball for outdoor and indoor play. Official size and weight.",
    description_krio: "Fayn basketbɔl fɔ ple",
    price: 55000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 32,
    is_active: true,
    is_featured: false,
    district: "Makeni",
    views_count: 289,
  },
  {
    id: "47",
    category_id: "8",
    name_en: "Swimming Goggles",
    name_krio: "Swim Glasis",
    description_en: "Anti-fog swimming goggles with UV protection. Comfortable fit for all ages.",
    description_krio: "Glasis fɔ swim",
    price: 22000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 48,
    is_active: true,
    is_featured: false,
    district: "Freetown",
    views_count: 156,
  },
  {
    id: "48",
    category_id: "8",
    name_en: "Sports Water Bottle",
    name_krio: "Spɔt Wata Bɔtul",
    description_en: "Large sports water bottle. BPA-free and leak-proof. Perfect for workouts and hiking.",
    description_krio: "Big wata bɔtul fɔ spɔt",
    price: 18000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 70,
    is_active: true,
    is_featured: false,
    district: "Bo",
    views_count: 234,
  },

  // Toys & Kids (Category 9)
  {
    id: "49",
    category_id: "9",
    name_en: "Building Blocks Set",
    name_krio: "Bildin Blɔk Sɛt",
    description_en: "Colorful building blocks set for creative play. Safe for children 3 years and above.",
    description_krio: "Blɔk dɛm fɔ pikin ple",
    price: 35000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 42,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 456,
  },
  {
    id: "50",
    category_id: "9",
    name_en: "Doll (African)",
    name_krio: "Afrika Dɔl",
    description_en: "Beautiful African doll with traditional clothing. Perfect gift for young girls.",
    description_krio: "Fayn Afrika dɔl fɔ pikin",
    price: 28000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 35,
    is_active: true,
    is_featured: true,
    district: "Bo",
    views_count: 389,
  },
  {
    id: "51",
    category_id: "9",
    name_en: "Toy Car Set",
    name_krio: "Toy Motoka Sɛt",
    description_en: "Set of 5 colorful toy cars. Durable plastic construction. Perfect for young boys.",
    description_krio: "5 toy motoka dɛm fɔ pikin",
    price: 32000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 50,
    is_active: true,
    is_featured: false,
    district: "Freetown",
    views_count: 423,
  },
  {
    id: "52",
    category_id: "9",
    name_en: "Coloring Books & Crayons",
    name_krio: "Kɔlɔ Buk ɛn Kreyɔn",
    description_en: "Coloring books with crayons set. Educational and fun for children.",
    description_krio: "Kɔlɔ buk ɛn kreyɔn fɔ pikin",
    price: 20000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 65,
    is_active: true,
    is_featured: false,
    district: "Makeni",
    views_count: 312,
  },
  {
    id: "53",
    category_id: "9",
    name_en: "Puzzle Set (Educational)",
    name_krio: "Pɔzul Sɛt",
    description_en: "Educational puzzle set for children. Helps develop problem-solving skills.",
    description_krio: "Pɔzul sɛt fɔ pikin lɔn",
    price: 25000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 38,
    is_active: true,
    is_featured: false,
    district: "Bo",
    views_count: 267,
  },
  {
    id: "54",
    category_id: "9",
    name_en: "Soft Teddy Bear",
    name_krio: "Sɔft Tɛdi Bɛya",
    description_en: "Cute and soft teddy bear. Safe for all ages. Perfect cuddly companion.",
    description_krio: "Sɔft tɛdi bɛya fɔ pikin",
    price: 30000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 45,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 534,
  },

  // Health & Wellness (Category 10)
  {
    id: "55",
    category_id: "10",
    name_en: "First Aid Kit",
    name_krio: "Fɛst Ɛd Kit",
    description_en: "Complete first aid kit with bandages, antiseptic, and medical supplies.",
    description_krio: "Kɔmplit fɛst ɛd kit fɔ ɛlp sik pipul",
    price: 55000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 40,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 489,
  },
  {
    id: "56",
    category_id: "10",
    name_en: "Multivitamins (Family Pack)",
    name_krio: "Vitamɛn Pak",
    description_en: "Family pack multivitamins for daily health support. Suitable for adults and children.",
    description_krio: "Vitamɛn pak fɔ ɔl famili",
    price: 42000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 55,
    is_active: true,
    is_featured: true,
    district: "Bo",
    views_count: 567,
  },
  {
    id: "57",
    category_id: "10",
    name_en: "Hand Sanitizer (500ml)",
    name_krio: "An Sanitayza",
    description_en: "Large bottle of hand sanitizer. Kills 99.9% of germs. Essential for hygiene.",
    description_krio: "An sanitayza fɔ kil jɛm",
    price: 15000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 120,
    is_active: true,
    is_featured: false,
    district: "Freetown",
    views_count: 678,
  },
  {
    id: "58",
    category_id: "10",
    name_en: "Blood Pressure Monitor",
    name_krio: "Blɔd Prɛsha Mɔnita",
    description_en: "Digital blood pressure monitor. Easy to use at home. Accurate readings.",
    description_krio: "Mashin fɔ chɛk blɔd prɛsha",
    price: 95000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 22,
    is_active: true,
    is_featured: false,
    district: "Freetown",
    views_count: 345,
  },
  {
    id: "59",
    category_id: "10",
    name_en: "Face Masks (Pack of 50)",
    name_krio: "Fes Mask Pak",
    description_en: "Disposable face masks pack. 3-layer protection. Comfortable and breathable.",
    description_krio: "50 fes mask fɔ protɛkt yu",
    price: 35000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 80,
    is_active: true,
    is_featured: false,
    district: "Bo",
    views_count: 423,
  },
  {
    id: "60",
    category_id: "10",
    name_en: "Herbal Tea (Wellness Blend)",
    name_krio: "Ɛbul Ti",
    description_en: "Natural herbal tea blend for wellness. Helps with digestion and relaxation.",
    description_krio: "Nachral ɛbul ti fɔ wɛlbɔdi",
    price: 20000,
    currency: "SLL",
    image_url: "/placeholder.svg?height=400&width=400",
    stock_quantity: 65,
    is_active: true,
    is_featured: true,
    district: "Freetown",
    views_count: 289,
  },
]

// Helper functions
export function getCategoryById(id: string): Category | undefined {
  return mockCategories.find((cat) => cat.id === id)
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return mockCategories.find((cat) => cat.slug === slug)
}

export function getProductsByCategory(categoryId: string): Product[] {
  return mockProducts.filter((product) => product.category_id === categoryId && product.is_active)
}

export function getFeaturedProducts(): Product[] {
  return mockProducts.filter((product) => product.is_featured && product.is_active).slice(0, 8)
}

export function getProductById(id: string): Product | undefined {
  return mockProducts.find((product) => product.id === id)
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return mockProducts.filter(
    (product) =>
      product.is_active &&
      (product.name_en.toLowerCase().includes(lowerQuery) ||
        product.name_krio.toLowerCase().includes(lowerQuery) ||
        product.description_en.toLowerCase().includes(lowerQuery) ||
        product.description_krio.toLowerCase().includes(lowerQuery)),
  )
}
